version: "3.7"
services:
  app:
    container_name: esus_app
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRES_URL_SERVER=${POSTGRES_URL_SERVER}
        - POSTGRES_PORT=${POSTGRES_PORT}
        - POSTGRES_DATABASE=${POSTGRES_DB}
        - POSTGRES_USERNAME=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - TIMEZONE=${TIMEZONE}
    stdin_open: true
    tty: true
    volumes:
      - ./install.sh:/var/www/html/install.sh
      - ./run.sh:/var/www/html/run.sh
      - ./data/e-SUS:/opt/e-SUS
    ports:
      - "${APP_PORT}:8080"
    networks:
      - postgres

networks:
  postgres:
    external: true
