version: "3"
services:
  psql:
    container_name: esus_psql
    restart: always
    image: postgres:13.5
    volumes:
      - ./data/psql_db:/var/lib/postgresql/data
      - ./data/backups:/home
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRESQL_PORT}:5432"
  app:
    container_name: esus_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRES_DATABASE=${POSTGRES_DB}
        - POSTGRES_USERNAME=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - TIMEZONE=${TIMEZONE}
    stdin_open: true
    tty: true
    volumes:
      - ./install.sh:/var/www/html/install.sh
      - ./run.sh:/var/www/html/run.sh
      - ./data/e-SUS:/opt/e-SUS
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - psql
  cron:
    container_name: esus_cron
    restart: always
    build:
      context: cron
      dockerfile: Dockerfile
    volumes:
      - ./cron/crontab.txt:/crontab.txt
      - ./cron/app:/home
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - CRON_PORT=${CRON_PORT}
    ports:
      - "${CRON_PORT}:5000"
    depends_on:
      - psql
